version: '3.1'

services:
  db:
    image: mariadb
    networks:
      - innogames
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  adminer:
    image: adminer
    networks:
      - innogames
    ports:
      - 8080:8080

networks:
  innogames:
